spring:
  application:
    name: sample-application
  sleuth:
    sampler:
      percentage: 1.0
logging:
  level:
    org.mousetail.sample: DEBUG
    org.springframework.cloud.sleuth: DEBUG
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  pattern:
#    console: '%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'